// External Dependencies
import { Inter } from "next/font/google";

// Internal Dependencies
import "./globals.css";
import { cn } from "@/lib/utils";
import Footer from "@/components/global/footer/footer";
import Navbar from "@/components/global/navbar/navbar";

const inter = Inter({
  weight: ["400", "500", "600", "700", "800", "900"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata = {
  title: "Flexpoint",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={cn(
          inter.className,
          "scroll-smooth bg-gradient-primary-from-top",
        )}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
